crowd_funding/urls.py
from django.contrib import admin
from django.urls import path, include
# those imports are for the static files
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings
from projects.views import index
from single_project.views import view_project
from users import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', index),
    path('users/', include('users.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
    path('social-auth/', include('social_django.urls', namespace="social")),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include,re_path
from users import views
from django.contrib.auth import views as auth_views

# Be careful setting the name to just /login use userlogin instead!
# SET THE NAMESPACE!
app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    re_path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
         views.activate, name='activate'),
    

    # path('password_reset/',
    #      auth_views.PasswordResetView.as_view(),
    #      {
    #          'post_reset_redirect': '/user/password_reset/done/'
    #      },
    #      name='password_reset'),
    #
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    #
    # path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
    #      auth_views.PasswordResetConfirmView.as_view(),
    #      {
    #          'post_reset_redirect': '/user/reset/done/'
    #      },
    #      name='password_reset_confirm'),
    #
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

users/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(
        max_length=11,
        validators=[RegexValidator('(01)[0-9]{9}',
                                   message="phone number is not valid")])
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)


def __str__(self):
    return self.user.username

users/forms.py
from django import forms
from django.forms import TextInput

from .models import UserProfileInfo
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
        )
        help_texts = {
            'username': None,
        }

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm password does not match."
            )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise forms.ValidationError('This Email is registered, use another email.')
        return email


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('phone',
                  'profile_pic')

users/views.py
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .tokens import account_activation_token
from users.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage


def index(request):
    return render(request, 'users/index.html')


@login_required
def special(request):
    return HttpResponse("You are logged in !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/users/user_login')


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.is_active = False
            user.save()

            # email activation
            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = user_form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()

            # return HttpResponse('Please confirm your email address to complete the registration')
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'users/registration.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username, password))
            return HttpResponseRedirect(redirect_to='/users/user_login')
    else:
        return render(request, 'users/login.html', {})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        login(request, user)
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')

users/templates/users/acc_active_email.html
{% autoescape off %}

    Hi {{ user.username }},
    Please click on the link to confirm your registration,
    http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}

{% endautoescape %}

users/templates/users/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
      {% load static %}
      <link rel="stylesheet" href="{% static 'users/css/bootstrap.css' %}" />
      <link rel="stylesheet" href="{% static 'users/js/bootstrap.js' %}" />
      <link rel="stylesheet" href="{% static 'users/css/index.css' %}" />
  </head>

  <body>
    <nav class="navbar navbar-dark bg-primary">

      {# Some logic on what to display for last item#}
      {% if user.is_authenticated %}
          <h3>Crowd Funding</h3>
        <a href="{% url 'logout' %}"><button>Logout</button></a>
      {% else %}
          <h4>Crowd Funding</h4>

          <button class="register">
            <a href="{% url 'users:register' %}">Register</a>
          </button>
          <button class="login">
            <a href="{% url 'users:user_login' %}">Login</a>
          </button>
      {% endif %}

    </nav>
    <div class="container">

    {% block body_block %}
    {% endblock %}

    </div>
  </body>
</html>

users/templates/users/index.html
{% extends "users/base.html" %}
{% block body_block %}

<div class="container">
    <h1>Welcome to the Djungle !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
</div>

{% endblock %}

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block body_block %}

  <div class="container">
      <h1>Login</h1>

{#      {% if form.errors %}#}
{#        {% for field in form %}#}
{#            {% for error in field.errors %}#}
{#                <div class="alert alert-danger">#}
{#                    <strong>{{ error|escape }}</strong>#}
{#                </div>#}
{#            {% endfor %}#}
{#        {% endfor %}#}
{#        {% for error in form.non_field_errors %}#}
{#            <div class="alert alert-danger">#}
{#                <strong>{{ error|escape }}</strong>#}
{#            </div>#}
{#        {% endfor %}#}
{#      {% endif %}#}
      {% if messages %}
        {% for message in messages %}
            alert(message);
        {% endfor %}
      {% endif %}

        <form method="post" action="{% url 'users:user_login' %}">
              {% csrf_token %}

        <label for="username-login">Username</label>
        <input class="username-login" type="text" name="username" placeholder="Username" >

        <label for="password-login">Password</label>
        <input class="password-login" type="password" name="password" placeholder="Password">

        <input type="submit" name="" value="Login">
        </form>

        <button class="btn btn-primary mb-2">
            <a href="{% url 'social:begin' 'facebook' %}" style="color:white">Login with Facebook</a>
        </button>
  </div>

{% endblock %}

users/templates/users/registration.html
{% extends "users/base.html" %}

{% load staticfiles %}

{% block body_block %}
  <div class="container">
      {% if registered %}
        <h1>Thank you for registering, Check your Email for Activating Link.</h1>
      {% else %}
        <h1>Registration</h1>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}
  </div>
{% endblock %}

users/templates/users/send_email.html
{% extends 'users/base.html' %}

{% block content %}

  <p>Please confirm your email address to complete the registration. </p>

{% endblock %}